[package]
name = "evebattle"
version = "0.1.0"
authors = ["<seb@ukr.net>"]

[lib]
name = "lib"
path = "src/lib/lib.rs"


[[bin]]
name = "evebattle"
path = "src/main.rs"

[dependencies]
    serde = "1.0.79"
    serde_derive = "1.0.79"
    serde_json = "1.0.32"
